// react/maoyan/src/components/film/Film.jsx
import React, { Component } from 'react'; 
import { Link } from 'react-router-dom';
import Movies from '../../common/movies/Movies';
import { getMovies, getMovies2, getMovies3 } from '../../api/axios/movies';
import Expected from '../../common/expected/Expected';
import { forceCheck } from 'react-lazyload';
import Debounce from '../../api/debounce/index';
import 'antd/dist/antd.css';
import './film.styl';
import { Tabs } from 'antd';
const { TabPane } = Tabs;
class Film extends Component {
  state = { 
    height: 0,
    movies: [],
    coming: [],
    movies3: []
   }
   componentDidMount() {
    let height = document.body.clientHeight - 144;
    this.setState({
      height
    })
    this.gMovie()
    this.gMovie2()
    this.gMovie3()
    this.refs.movieHot.addEventListener('scroll', Debounce(() => this.cal(), 400))
  }
  cal = () => {
    let high1 = this.refs.movieHot.scrollHeight;
    let high2 = this.refs.movieHot.clientHeight;
    if (this.refs.movieHot.scrollTop > high1 - high2 - 2) {
      this.gMovie()
    }
  }
  handleScroll = () => {
    let high3 = this.refs.expect.scrollHeight;
    let high4 = this.refs.expect.clientHeight;
    if (this.refs.expect.scrollTop > high3 - high4 - 2) {
      this.gMovie3()
    }
    forceCheck()
  }
  gMovie = () => {
    getMovies().then(res => {
      // console.log(res)
      this.setState({
        movies: this.state.movies.concat(res.data.data.movieList)
      })
    })
  }
  gMovie2 = () => {
    getMovies2().then(res => {
      // console.log(res)
      this.setState({
        coming: res.data.data.coming
      })
    })
  }
  gMovie3 = () => {
    getMovies3().then(res => {
      // console.log(res)
      this.setState({
        movies3: this.state.movies3.concat(res.data.data.coming)
      })
    })
  }
  render() {
    const { height, movies, coming, movies3 } = this.state;
    return (
      <div className="App">
      <header className="header-nav">猫眼电影</header>
      <div className="topbar">
        <div className="left">
          <span className="city-name">南昌</span>
          <i className="arrow"></i>
        </div>
        <div className="mid">
          <Tabs defaultActiveKey="1">
            <TabPane tab="正在热映" key="1">
              <div className="movie" ref="movieHot" style={{height: `${height}px`}} onScroll={forceCheck}>
                {
                  movies.map((movie, index) => {
                    return (
                      <Movies movie={movie} key={index}/>
                    )
                  })
                }
              </div>
            </TabPane>
            <TabPane tab="即将上映" key="2">
              <div className="most-expected" style={{height: `${height}px`}} onScroll={this.handleScroll} ref="expect">
                <p className="title">近期最受期待</p>
                <div className="most-expected-list">
                  {
                    coming.map((come, index) => {
                      return (
                        <Expected come={come} key={index}/>
                      )
                    })
                  }
                </div>
                <div className="coming-list">
                  <p className="group-date">7月12日 周五</p>
                  {
                    movies3.map((movie, index) => {
                      return (
                        <Movies movie={movie} key={index}/>
                      )
                    })
                  }
                </div>
              </div>
            </TabPane>
          </Tabs>
        </div>
        <div className="right">
          <Link to="/search">
          <div className="search-icon"></div>
          </Link>
        </div>
      </div>
    </div>
    );
  }
}

export default Film;

// Vue/maoyan-movie/src/components/Film.vue
<template>
  <div class="wrapper">
    <v-header>猫眼电影</v-header>
    <div class="topbar">
      <div class="left">
        <span class="city-name">南昌</span>
        <i class="arrow"></i>
      </div>
      <div class="mid">
        <el-tabs v-model="activeName" @tab-click="handleClick">
          <el-tab-pane label="正在热映" name="first">
            <div class="movie" ref="movieAll">
              <div class="item" v-for="(movie, index) in movies" :key="index">
                <Movie :movie="movie"/>
              </div>
            </div>
          </el-tab-pane>
          <el-tab-pane label="即将上映" name="second">
             <div class="most-expected" ref="expect">
                <p class="title">近期最受期待</p>
                <div class="most-expected-list">
                  <div class="item-expect" v-for="(movie2, index2) in coming" :key="index2">
                    <Expected :come="movie2"/>
                  </div>
                </div>
                <div class="coming-list">
                  <p class="group-date">7月12日 周五</p>
                  <div class="item-come" v-for="(movie3, index3) in movies3" :key="index3">
                    <Movie :movie="movie3"/>
                  </div>
                </div>
              </div>
          </el-tab-pane>
        </el-tabs>
      </div>
      <div class="right">
        <router-link to="/search">
          <div class="search-icon"></div>
        </router-link>
      </div>
    </div>
  </div>
</template>

<script>
import Header from '../common/Header'
import Movie from '../common/Movie'
import Expected from '../common/Expected'
import { getMovies, getMovies2, getMovies3 } from '../api/axios/movies';
import debounce from '../api/debounce/index';
export default {
  name: 'Film',
  data() {
    return {
      activeName: 'first',
      movies: [],
      coming: [],
      movies3: []
    }
  },
  created() {
    getMovies().then(res => {
      this.movies = res.data.data.movieList
    })
    getMovies2().then(res => {
      this.coming = res.data.data.coming
    })
    getMovies3().then(res => {
      this.movies3 = res.data.data.coming
    })
  },
  mounted() {
    this.$refs.movieAll.addEventListener('scroll', debounce(() => {
      // console.log(this.$refs.movieAll.scrollTop)
      let high1 = this.$refs.movieAll.scrollHeight;
      let high2 = this.$refs.movieAll.clientHeight;
      if (this.$refs.movieAll.scrollTop > high1 - high2 - 5) {
        getMovies().then(res=> {
          this.movies = this.movies.concat(res.data.data.movieList)
        })
      }
    }, 400))
    this.$refs.expect.addEventListener('scroll', debounce(() => {
      let high3 = this.$refs.expect.scrollHeight;
      let high4 = this.$refs.expect.clientHeight;
      if (this.$refs.expect.scrollTop > high3 - high4 - 5) {
        getMovies3().then(res=> {
          this.movies3 = this.movies3.concat(res.data.data.coming)
        })
      }
    }, 400))
  },
  components: {
    'v-header': Header,
    Movie,
    Expected
  },
  methods: {
    handleClick(tab, event) {
      // console.log(tab, event);
    }
  }
}
</script>

<style scoped lang="stylus">
.topbar
  display flex
  border-bottom 1px solid #e6e6e6
  height 44px

.movie
  padding-right 10px
  padding-left 15px
  overflow-y scroll
  height 80vh

.left, .mid, .right
  flex 1

.left
  font-size 15px
  margin auto
  text-align left
  padding-left 15px

.arrow
  display inline-block
  width 0
  height 0
  border 4px solid #b0b0b0
  border-left-color transparent
  border-right-color transparent
  border-bottom-color transparent
  margin-left 4px
  margin-top 5px

.right
  position relative
  padding-right 15px

.search-icon
  width 60px
  height 44px
  background url("../assets/images/search.png") 40px 12px no-repeat
  background-size 20px
  right 15px
  position absolute

.most-expected 
  padding 12px 0px
  background-color #fff
  margin-bottom 10px
  text-align left
  position fixed
  left 15px
  width 98vw
  padding-right 5%
  overflow-y scroll
  height 80vh
  box-sizing border-box
  margin-top 5px
  padding-top 7px

.title 
  margin 0 0 12px
  font-size 14px
  color #333

.most-expected-list 
  overflow scroll
  white-space nowrap
  margin-right 3%
  .item-expect
    display inline-block

.group-date
  margin 0
  font-size 14px
  color #333
.item-come
  position relative
.item 
  position relative
</style>
<style lang="stylus">
.el-tabs__nav
  height 44px
.el-tabs__item
  font-size 15px
  font-weight 700
  &:hover
    color black
.is-active
  font-style 15px
  font-weight 700
  color #ef4238 !important
.el-tabs__nav-wrap::after
  height 0
.el-tabs__active-bar
  background-color #ef4238 !important
.el-tabs__header 
  margin 0
.el-tabs__content
  position fixed
  left 0
  width 100vw
</style>
